class_name Packets

enum ServerPacket {
	CREATE_BLOCK_CHUNK,
	PLAYER_CHUNK_INDEX,
	UPDATE_BLOCK,
	CREATE_ENTITY,
	DESTROY_ENTITY,
	ENTITY_DATA,
	ASSIGN_PLAYER,
	CREATE_INVENTORY
}

enum ClientPacket {
	ACTION_PRESSED,
	ACTION_RELEASED,
	CHECK_PLAYER_POSITION,
	CHECK_BLOCK_UPDATE,
	SELECT_ITEM
}
